service: ${self:custom.hcaIngest.name}-clerk

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  hcaIngest: ${file(../hcaIngest.yml)}
  private: ${file(../private.yml)}
  events: ${file(../events.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.private.region}

functions:
  logger:
    handler: handler.logger
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":"
                - ${self:custom.hcaIngest.name}
                - "-"
                - ${self:custom.events.metadata-received}
          topicName: ${self:custom.hcaIngest.name}-${self:custom.events.metadata-received}