service: ${self:custom.hcaIngest.name}-clerk

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  hcaIngest: ${file(../hcaIngest.yml)}
  private: ${file(../private.yml)}
  events: ${file(../events.yml)}
  tables: ${file(../tables.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.private.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - "table/"
            - ${self:custom.hcaIngest.name}
            - "-"
            - ${self:custom.tables.ledger}

functions:
  logger:
    handler: handler.logger
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":"
                - ${self:custom.hcaIngest.name}
                - "-"
                - ${self:custom.events.metadata-received}
          topicName: ${self:custom.hcaIngest.name}-${self:custom.events.metadata-received}
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":"
                - ${self:custom.hcaIngest.name}
                - "-"
                - ${self:custom.events.submission-created}
          topicName: ${self:custom.hcaIngest.name}-${self:custom.events.submission-created}
    environment:
      LEDGER_TABLE: ${self:custom.hcaIngest.name}-${self:custom.tables.ledger}

resources:
  Resources:
    LedgerDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.hcaIngest.name}-${self:custom.tables.ledger}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5